name: Build Windows EXE

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install PyInstaller (and any other required packages)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      # Step 4: Build the executable using your PyInstaller command
      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --add-data "config.json;." --add-data "app_icon.ico;." --add-data "barcode_icon.png;." --icon="app_icon.ico" --name "Book Check-In Service" checkin.py

      # Step 5: Upload the built EXE to the GitHub release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Book Check-In Service.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
